// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CardSelect: typeof import('./components/CardSelect.vue')['default']
    CategoryTag: typeof import('./components/CategoryTag.vue')['default']
    CollectionList: typeof import('./components/CollectionList.vue')['default']
    ConditionRating: typeof import('./components/ConditionRating.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    InflationStatistic: typeof import('./components/InflationStatistic.vue')['default']
    ItemAvatar: typeof import('./components/ItemAvatar.vue')['default']
    ItemBreadcrumb: typeof import('./components/ItemBreadcrumb.vue')['default']
    ItemInfoCard: typeof import('./components/ItemInfoCard.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    OwnerTag: typeof import('./components/OwnerTag.vue')['default']
    PackageCard: typeof import('./components/PackageCard.vue')['default']
    PictureGroup: typeof import('./components/PictureGroup.vue')['default']
    PictureSelect: typeof import('./components/PictureSelect.vue')['default']
    PriceInfo: typeof import('./components/PriceInfo.vue')['default']
    PriceList: typeof import('./components/PriceList.vue')['default']
    PublicTag: typeof import('./components/PublicTag.vue')['default']
    README: typeof import('./components/README.md')['default']
    SellTag: typeof import('./components/SellTag.vue')['default']
    StepCard: typeof import('./components/StepCard.vue')['default']
    StorageCard: typeof import('./components/StorageCard.vue')['default']
  }
}

export { }
